services:
  postgres:
    image: postgres:15-alpine
    container_name: course_db
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./table.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - course_network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: course_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/course_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    networks:
      - course_network


  #   добавил сервис для frontend
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: course_frontend
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - course_network

volumes:
  postgres_data:

networks:
  course_network:
    driver: bridge
